[[companies]]
name = "Steinbauer Performance"
start = "2010-10-15"
end = "2016-08-12"
positions = []

[[companies]]
name = "LiveRamp"
start = "2016-08-15"
end = "2021-12-01"
positions = [
  { name = "Software Engineer", start = "2021-12-01" },
  { name = "Tech Lead", start = "2018-05-01" },
]
